# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Check bronze table schema
# MAGIC drop table food_inspection.bronze.dallas_inspections_bronze;
# MAGIC drop table food_inspection.bronze.chicago_inspections_bronze;

# COMMAND ----------

# MAGIC %sql
# MAGIC ALTER TABLE food_inspection.raw.dallas_inspections 
# MAGIC SET TBLPROPERTIES (delta.enableChangeDataFeed = true);

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC ALTER TABLE food_inspection.raw.chicago_inspections 
# MAGIC SET TBLPROPERTIES (delta.enableChangeDataFeed = true);

# COMMAND ----------

from pyspark.sql.functions import *
import re

def clean_column_names(df):
    """Convert column names to database-friendly format"""
    for col_name in df.columns:
        clean_name = re.sub(r'[^\w]', '_', col_name)
        clean_name = re.sub(r'_+', '_', clean_name)
        clean_name = clean_name.strip('_').lower()
        df = df.withColumnRenamed(col_name, clean_name)
    return df

# Read and clean Chicago data
chicago_raw = spark.read.parquet("/Volumes/food_inspection/bronze/raw/chicago.parquet")
chicago_clean = clean_column_names(chicago_raw)

# Create raw table
chicago_clean.write.mode("overwrite").saveAsTable("food_inspection.raw.chicago_inspections")

# Read and clean Dallas data
dallas_raw = spark.read.parquet("/Volumes/food_inspection/bronze/raw/dallas.parquet")
dallas_clean = clean_column_names(dallas_raw)

# Create raw table
dallas_clean.write.mode("overwrite").saveAsTable("food_inspection.raw.dallas_inspections")

print("✅ Created raw tables with clean column names")

# COMMAND ----------

# MAGIC %sql
# MAGIC DESCRIBE food_inspection.silver.dallas_inspections_silver;
# MAGIC

# COMMAND ----------

# MAGIC %md
# MAGIC SCD validation
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC select  * from food_inspection.gold.dim_restaurant_scd2 where restaurant_id_nk='CHI_0.0_41.77152209276612_-87.61324807169647';

# COMMAND ----------

# MAGIC %sql
# MAGIC update food_inspection.raw.chicago_inspections set  dba_name='WINGS GREENS & THINGS CO' where dba_name='WINGS GREENS & THINGS';

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from food_inspection.gold.fact_inspection where data_workflow_name='DAL' and result='Pass'

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from food_inspection.raw.dallas_inspections limit 10
